version: '3.8'

services:
  web-generator-loc:
    build: 
      context: ../
      dockerfile: deploy/Dockerfile
    command: gunicorn ctjot.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - ../ct.sfc:/home/ctjot/web/ct.sfc
      - static_volume:/home/ctjot/web/staticfiles
    expose:
      - 8000
    env_file:
      - ./.env.loc
      - ./.env.loc.db

volumes:
  static_volume:

